### ISSUE TITLE
npm or yarn

### ISSUE THREAD

**Issue by stefanbauer** [tailwindcss/docs#1]
Your README relates to npm, but in the repo is a `yarn.lock`. I wanted to create a PR, but thought it doesn't make sense if I don't know if you'd prefer yarn or npm.

**Comment by adamwathan** [comment]
I use yarn but it shouldn't matter for a PR unless you are adding a dependency and changing the lock file. The common approach seems to be to document npm instructions, assuming that anyone who uses yarn already knows how to translate them.

**Comment by stefanbauer** [comment]
For sure, but what I meant is: You have instructions like `npm install`, but there is no `package-lock.json` like the `yarn.lock`. So you don't rely on specific versions?! If someone uses yarn, he gets installed exactly that versions, that are defined in `yarn.lock`, but for `npm` this is not true. Not sure if that is a good idea.
