### ISSUE TITLE
Text overflow in Cards example

### ISSUE THREAD

**Issue by mhanberg** [tailwindcss/docs#12]
![image](https://user-images.githubusercontent.com/5523984/37733877-e295f20e-2d1f-11e8-80b9-0bcba5004f83.png)

Hi, wasn't sure if this was intentional or not so I thought I would drop it here.

I plan on trying out tailwind soon, thanks for all the work!

**Comment by adamwathan** [comment]
Ah yeah that's the image alt text, not sure why that's even being rendered there for you instead of the image itself 🤔 Any suggestions on how the alt text would be best styled?

**Comment by mhanberg** [comment]
Oh, interesting, I didn't realize it was the alt-text. The image may not have loaded due to network settings (this screenshot was taken on my work computer).

Considering the alt-text is mostly used for accessibility and SEO, I'm not sure the styling is _super_ important. Maybe use ellipsis for the overflow and show the full text on hover? Not sure how much of that is possible with CSS.
