### ISSUE TITLE
(text-style) Focus doesn’t transform to uppercase

### ISSUE THREAD

**Issue by SHxKM** [tailwindcss/docs#128]
See the focus uppercase example here: https://next.tailwindcss.com/docs/text-style

**Comment by adamwathan** [comment]
Thanks, yeah this whole page is basically out of date. Needs to be split into four separate pages, will get to this Monday if I don't have time this weekend.

**Comment by SHxKM** [comment]
Let me know if I can help. This is a great project and the docs are more than decent for this stage.

**Comment by adamwathan** [comment]
Updated!
