### ISSUE TITLE
Controlling File Size page needs updating

### ISSUE THREAD

**Issue by davecalnan** [tailwindcss/docs#136]
I want to update [Controlling File Size](https://next.tailwindcss.com/docs/controlling-file-size). Build sizes, the number of colours, screens, and the documentation examples are outdated.

I spent way too long making a tool to analyse tailwind build sizes for different configs: [https://github.com/davecalnan/measure-tailwindcss-build-size](https://github.com/davecalnan/measure-tailwindcss-build-size)

It calculates an output like:
```
┌───────────────────┬──────────┬──────────┬─────────┬─────────┬──────────────┐
│ Config            │ Original │ Minified │ Gzipped │ Classes │ Declarations │
├───────────────────┼──────────┼──────────┼─────────┼─────────┼──────────────┤
│ default.config.js │ 472.5K   │ 347.7K   │ 58.1K   │ 8271    │ 8336         │
├───────────────────┼──────────┼──────────┼─────────┼─────────┼──────────────┤
│ extend.config.js  │ 474.9K   │ 349.4K   │ 58.5K   │ 8316    │ 8381         │
├───────────────────┼──────────┼──────────┼─────────┼─────────┼──────────────┤
│ replace.config.js │ 224.0K   │ 155.0K   │ 21.9K   │ 4131    │ 4196         │
└───────────────────┴──────────┴──────────┴─────────┴─────────┴──────────────┘
```

I'm going to create a pull request with the relevant updates to the page.

**Comment by davecalnan** [comment]
Update build sizes for 1.0 builds  …
I calculated and updated each build size mentioned. For each I started with the default empty config and replaced colors/screens as mentioned in the doc. I used `npx tailwind build` to build. [`clean-css`](https://github.com/jakubpawlowicz/clean-css) to minify using the default settings and [`node-gzip`](https://github.com/Rebsos/node-gzip), a wrapper around node [`zlib.gzip`](https://nodejs.org/api/zlib.html#zlib_zlib_gzip_buffer_options_callback) to compress.

I've double-checked my calculations as shown below. If you want to run them yourself please feel free to clone https://github.com/davecalnan/measure-tailwindcss-build-size.

<img width="817" alt="Screenshot 2019-04-03 09 03 56" src="https://user-images.githubusercontent.com/23709612/55462781-6f0a4700-55ef-11e9-8981-df07ac6ca2ef.png">

**Comment by adamwathan** [comment]
This is amazing, nice job! I sent you a PR that adds Brotli for comparison as well since Tailwind compresses so much better with it 🤙 going to merge your changes now and add the Brotli numbers as well. Thanks again!

**Comment by davecalnan** [comment]
Didn't know about Brotli, thanks for that! Glad to contribute 👍🏻
