### ISSUE TITLE
compiling failure

### ISSUE THREAD

**Issue by MiloudiMohamed** [tailwindcss/docs#16]
I've tried to install the docs locally, but when i run `npm run dev` i got: 
**'.' is not recognized as an internal or external command,** , 
I'm on windows 10 64bits 
i got the latest npm version 5.8.0
thanks

**Comment by MichaelDeBoey** [comment]
Same here 😕

**Comment by adamwathan** [comment]
@MichaelDeBoey are you on Windows as well? I'm able to build locally still on macOS without any issues but don't have any way to test on Windows. Can someone share a full stack trace?

**Comment by MichaelDeBoey** [comment]
@adamwathan I'm on macOS and re-cloned the repo and that seemed to solve the  problem 🙂

**Comment by leonardeveloper** [comment]
Same here, all commands is working but when I try to check on http://localhost:8080 it says "This site can’t be reached"

**Comment by leonardeveloper** [comment]
Same error with me, I'm using windows as well.

**Comment by adamwathan** [comment]
Not really sure but definitely some Windows specific thing, here's what I found by searching, might lead you to an answer:

https://stackoverflow.com/questions/20765337/how-to-fix-is-not-an-internal-or-external-command-error

**Comment by AdamKeen** [comment]
Yeah that worked!, thank you

**Comment by missmatsuko** [comment]
Can this be closed?
