### ISSUE TITLE
Impact line colllides with the header

### ISSUE THREAD

**Issue by dilantha** [tailwindcss/docs#166]
Hey @adamwathan,

The impact line in the upgrade guide needs some space.

https://next.tailwindcss.com/docs/upgrading-to-v1/

![image](https://user-images.githubusercontent.com/450922/56073001-dccd2480-5de0-11e9-8d4b-c309c330af7a.png)

`<p class="italic font-normal text-gray-600 -mt-2">Impact: All users, Effort: Moderate</p>`

Removing the `-mt-2` seems to fix it.

Cheers,
Dilantha

**Comment by adamwathan** [comment]
Just pushed a fix, thanks!
