### ISSUE TITLE
"Only run PurgeCSS during production builds for faster development builds" is risky advice

### ISSUE THREAD

**Issue by garygreen** [tailwindcss/docs#167]
I notice the docs you recommend to only run PurgeCSS during production builds - although this advice seems sound, it's actually a bit risky because you may end up having totally different functionality in development than in production.

If you strip out unused css *in development* - you'll get instant feedback whether your PurgeCSS rules are working correctly and it'll give you 100% confidence it'll work in production. But if PurgeCSS strips out the wrong css after-the-fact then you'll get a bit of a headache working out why it's broken in production but worked perfectly fine locally.

Just a few things to consider, anyway.

I personally haven't found the right solution either, but to me it makes sense to purge in all environments to avoid deploying potentially broken code. It would be nice if there was a way to cache/speed up PurgeCSS, maybe `cache-loader` can help.

**Comment by adamwathan** [comment]
Yeah there's a bit of a risk there for sure. The challenge is that if you purge in development, your watcher needs to watch all of your templates for changes too which is not super easy to set up when working in a context that isn't pure-webpack, like building a Laravel app with Blade templates or a Rails app with ERB templates. It also doesn't help that purging can be slow, like you mentioned.

Personally I'm okay with that risk and it's only ever bitten me one time when I created some custom classes that used the `%` character and didn't update my Purgecss regex to account for it, but it would probably be a good idea to talk about it a bit in the docs.

**Comment by CvX** [comment]
I had a similar concerns about potential issues with shipping a CSS build to production that's different to the one I'm working with in the dev env. I've tried enabling PurgeCSS locally, only to realize moments later how important to my workflow is manipulating my app's style in DevTools: trying out style changes live in the browser, by adding and removing CSS classes. With purging enabled, I'm limited to the set of classes that are already used within the app, and that's not ideal.

Just saying that PurgeCSS's performance isn't the only argument for enabling it just in production builds. 🙂
