### ISSUE TITLE
[FEATURE ] Component section

### ISSUE THREAD

**Issue by cloudstudio** [tailwindcss/docs#182]
👋 Hey @adamwathan congratulations one more time for this framework!

I love this, but It would be nice to have more components something like this https://getuikit.com/docs/introduction ( components ) 

We are a lot of people here, near 11k stars, could be nice open a "official" component page , so we can make PR for this one.

I can help with this, and sure that many more people too.

It is an option ? thanks!

**Comment by adamwathan** [comment]
We have some example components in the docs already but are planning on adding more in the near future. We're also working on a commercial component kit so we can continue to fund development on Tailwind itself which we're hoping to have ready in the Fall 👍
