### ISSUE TITLE
Small issue in Migration Guide

### ISSUE THREAD

**Issue by hacknug** [tailwindcss/docs#209]
Inside the migration guide [Item 13](https://tailwindcss.com/docs/upgrading-to-v1#13-add-inline-to-any-replaced-elements-img-video-etc-that-should) asks users to add `inline` to their replace elements when they want them to be `display: block`. Should probably be `display: inline`.

```diff
- 13. Add `inline` to any replaced elements (`img`, `video`, etc.) that should be `display: block`
+ 13. Add `inline` to any replaced elements (`img`, `video`, etc.) that should be `display: inline`
```

Can open a PR for this tomorrow-ish. Feel free to assign me this issue if you want me to do so.

**Comment by adamwathan** [comment]
Fixed, thanks!
