### ISSUE TITLE
https://tailwindcss.com/community page links seem broken.

### ISSUE THREAD

**Issue by Nothing-Works** [tailwindcss/docs#213]
![Untitled](https://user-images.githubusercontent.com/18606648/57813141-474bf880-77c3-11e9-94f8-b2f200a1996b.png)

these links seem not to redirect to the pages.

**Comment by adamwathan** [comment]
Fixed, thanks! 

https://github.com/tailwindcss/docs/commit/226c2e0ee5ada5e2b2031a3c3c6ea6140dfb6a58

BTW my company is literally NothingWorks Inc 😅

![image](https://user-images.githubusercontent.com/4323180/57852624-9be67800-77b1-11e9-8d1a-eb6205a771ee.png)

**Comment by adamwathan** [comment]
Thought I fixed it but I was wrong 🤙 Working on a real fix now!

**Comment by adamwathan** [comment]
Should actually be fixed now. DIY Turbolinks bullshit bites me again 🙃

https://github.com/tailwindcss/docs/commit/0dfd9645b2f4c0c4e7c643a6aa6cf0c4a4be4156

**Comment by Nothing-Works** [comment]
@adamwathan hahahaha.... nice company man!!!
