### ISSUE TITLE
Where offline docs

### ISSUE THREAD

**Issue by nikolaokonesh** [tailwindcss/docs#233]
Where offline docs?

**Comment by adamwathan** [comment]
You can clone this repo if you'd like to have access to the docs offline, not sure what other options there are.

**Comment by KeysiJones** [comment]
> Where offline docs?

Hello world ! just download it from mega, here is the link !
https://mega.nz/#!8DpVFLxB!U25M0tnwMH2zZv2fQedcKAxeiYccVIo4vh9xs8ShWhk

i hope i helped you

**Comment by bella13mo** [comment]
**where offline Docs**

**Comment by MRKPRO360** [comment]
![Screenshot_20201201-181037_Chrome](https://user-images.githubusercontent.com/75315042/100743042-e9fbb480-3405-11eb-8585-333d25956468.jpg)

> why this is happened?

**Comment by yob-yob** [comment]
I Think a good option would be to support [devdocs](https://devdocs.io)? [zealdocs](https://zealdocs.org)? 

and here's how to make one https://kapeli.com/docsets

**Comment by harshverma036** [comment]
> > Where offline docs?
> 
> Hello world ! just download it from mega, here is the link ! just unzip it and open the index.html file :)
> https://mega.nz/#!8DpVFLxB!U25M0tnwMH2zZv2fQedcKAxeiYccVIo4vh9xs8ShWhk
> 
> i hope i helped you

thank you ;)

**Comment by KeysiJones** [comment]
> > > Where offline docs?
> > 
> > 
> > Hello world ! just download it from mega, here is the link ! just unzip it and open the index.html file :)
> > https://mega.nz/#!8DpVFLxB!U25M0tnwMH2zZv2fQedcKAxeiYccVIo4vh9xs8ShWhk
> > i hope i helped you
> 
> thank you ;)

You are welcome my friend.

**Comment by naveennamani** [comment]
You can simply build the documentation yourself for offline use. Read my following post for the build steps. It's very easy.
https://dev.to/naveennamani/generate-offline-documentation-of-tailwindcss-in-5-minutes-3o79

**Comment by StefanoTesla** [comment]
> > Where offline docs?
> 
> Hello world ! just download it from mega, here is the link ! just unzip it and open the index.html file :) https://mega.nz/#!8DpVFLxB!U25M0tnwMH2zZv2fQedcKAxeiYccVIo4vh9xs8ShWhk
> 
> i hope i helped you

Thank you from the airport

**Comment by chrismapeesa** [comment]
thanks

**Comment by justingolden21** [comment]
Tried this a few times. It's over a gb to download the repo and takes minutes to hours and often fails. Once I actually got it downloaded, it wouldn't build successfully either. Seems to be a lot of images and videos in the repo, which are also tracked in git history. Makes it basically unusable offline. Would be nice to make the docs a PWA so you can install offline on any computer or phone and then only cache the most recent 20 pages that have been visited in the past month or something.

**Comment by geek-nath** [comment]
> > Where offline docs?
> 
> Hello world ! just download it from mega, here is the link ! just unzip it and open the index.html file :) https://mega.nz/#!8DpVFLxB!U25M0tnwMH2zZv2fQedcKAxeiYccVIo4vh9xs8ShWhk
> 
> i hope i helped you

This is the best suggestion I've seen so far. Thanks

**Comment by Bilal-SoftwareDev** [comment]
> > Where offline docs?
> 
> Hello world ! just download it from mega, here is the link ! just unzip it and open the index.html file :) https://mega.nz/#!8DpVFLxB!U25M0tnwMH2zZv2fQedcKAxeiYccVIo4vh9xs8ShWhk
> 
> i hope i helped you

do u have the latest one 🙏

**Comment by midnight-wonderer** [comment]
Tailwind's docs are down today, which is leading to my little adventure.
If you come to this page in the future because of the same issue, [see here](https://github.com/tailwindlabs/tailwindcss/discussions/2217#discussioncomment-11116024).

Thanks to yob-yob, who posted about [Zeal](https://zealdocs.org/) on this thread.
