### ISSUE TITLE
Use hsl format for colors

### ISSUE THREAD

**Issue by kabalage** [tailwindcss/docs#248]
I found myself inspecting the color palette and converting colors to hsl format to figure out relations between the chosen values. Showing the color values in hsl instead of hex would be much more useful to those who would like to alter the default palette. Changing the palette for at least the brand color must be common. What do you think?

Pages:

- https://tailwindcss.com/docs/customizing-colors#default-color-palette
- https://tailwindcss.com/docs/background-color/
- https://tailwindcss.com/docs/text-color/

**Comment by CvX** [comment]
See discussion in https://github.com/tailwindcss/tailwindcss/pull/967 🙂

**Comment by kabalage** [comment]
Oops, I only checked the issues in here. :)
