### ISSUE TITLE
Docs translation

### ISSUE THREAD

**Issue by GraxMonzo** [tailwindcss/docs#251]
How I can translate docs?

**Comment by DCzajkowski** [comment]
I personally think translating the docs is a very bad idea. The translations have to be updated, which is not easy. They also may not be accurate and every change to the English docs requires N changes into language docs proving it nearly impossible to maintain. This often leads to docs getting out of sync making translations poor quality.

On the contrary, writing books or articles in different languages helps a lot and gives a lot of value. I'd suggest doing that instead 😉 It's much less work and benefits the community hugely. Have fun! 😊
