### ISSUE TITLE
focus-within example

### ISSUE THREAD

**Issue by chrislabarge** [tailwindcss/docs#258]
The example for https://tailwindcss.com/docs/pseudo-class-variants#focus-within demos a input element that changes its container's border color on focus.  However the following snippet on how to allow `focus-within` in the configuration provides an example on setting it for a backgroundColor.

```
// tailwind.config.js
module.exports = {
  // ...
  variants: {
    backgroundColor: ['focus-within'],
  },
}
```

For consistency, I propose changing this config snippet to use `borderColor`

**Comment by adamwathan** [comment]
Fixed, thanks.
