### ISSUE TITLE
Font-family sans [Open Sans] example is not escaped

### ISSUE THREAD

**Issue by FreDeRoover** [tailwindcss/docs#261]
On the [font-family](https://tailwindcss.com/docs/font-family#font-families) section, Open Sans is not escaped.

Instead of **'body': ['Open Sans', ...],**, one of the following would be correct **'body': ['"Open Sans"', ...],** or **'sans': ['Open\\\ Sans', ...],**.

I'll be creating a pull request later this evening.

**Comment by adamwathan** [comment]
Doesn't need to be escaped, you can use font families with spaces without quotes as long as the font doesn't start with a number.
