### ISSUE TITLE
Reuse docs layout for Seed homepage

### ISSUE THREAD

**Issue by MartinKavik** [tailwindcss/docs#292]
Hi!
I'm contributor to Rust framework [Seed](https://github.com/David-OConnor/seed) and I've created quickstart [template](https://github.com/MartinKavik/seed-quickstart-webpack) with Tailwind.

I don't see LICENSE file in this repo, so I'm curious if there is chance to clone it, replace content and some parts of UI and use it as Seed's homepage. There will credits and link to this repo / Tailwind of course.

---

OT:
@adamwathan It would nice to have Tailwind in Rust/WASM world. Just ideas - I can rewrite this docs aka Seed's new homepage into Seed and create a new template from it, or Rust-only Tailwind would be awesome.

**Comment by hacknug** [comment]
Related to #58 and #75.

**Comment by MartinKavik** [comment]
@hacknug Thanks, I didn't find #58. 
I'll wait a little bit because of OT section, but issue is probably resolved.

**Comment by adamwathan** [comment]
For now would prefer to keep the site design proprietary, sorry 😕

**Comment by cameron-elliott** [comment]
@MartinKavik 
The following may be of interest to you if you didn't discover them already:
http://jigsaw-docs-staging.tighten.co/
https://github.com/tightenco/jigsaw-docs-template
There is also a separate blog and a coming combined project (blog+docs)

**Comment by MartinKavik** [comment]
@cameron-elliott 
Thanks! I see them for the first time.
Template is nice but I have 2 UX problems with it:
   - Guide list (left menu on the desktop view) and header aren't sticky or fixed - once you scroll down you can't go to another guide or search.
   - There are no other links like GitHub and side bar "On this page" like on Jigsaw official [docs](https://jigsaw.tighten.co/docs/installation/).

I'm already writing something similar with Rust and TailwindCSS so I can use your links at least for inspiration, thanks.
