### ISSUE TITLE
Printable pdf cheatsheet

### ISSUE THREAD

**Issue by skyronic** [tailwindcss/docs#320]
I made a concise one-page reference for my most frequently used tailwind classes ([a picture here](https://i.imgur.com/L2Qftqq.jpg)), and it's been super helpful (made it in MS Word as a quick fix).

I'm aware there's already some online quick references for tailwind. However, if you're interested in having a print-ready PDF as a part of the main docs, I'd be happy to contribute a proper solution.

Please feel free to close this issue if you feel this is more trouble than it's worth. I know printed references isn't everyone's cup of tea.

**Comment by narwy** [comment]
You can make a community page and make it print ready, for those who are interested.

**Comment by skyronic** [comment]
That sounds like a good plan, I'll do that and see if there's folks interested!
