### ISSUE TITLE
Improve top/right/bottom/left/inset documentation

### ISSUE THREAD

**Issue by KKSzymanowski** [tailwindcss/docs#324]
The documentation on customising the `top-*`, `bottom-*`, `inset-*` etc. classes isn't very clear. I needed to guess that the `inset` object in the configuration file actually manages all `top-`, `right-`, `bottom-` and `left-` classes. 

I would suggest adding a sentence which explains that for future users but since I'm not a native english speaker I would rather leave the wording to someone who is.

**Comment by royvanv** [comment]
> I needed to guess that the `inset` object in the configuration file actually manages all `top-`, `right-`, `bottom-` and `left-` classes.

It is mentioned right under the "Customizing" section.

**Comment by KKSzymanowski** [comment]
> It is mentioned right under the "Customizing" section.

Yeah, kind of, but it wasn't clear when I first read it. If you think I'm talking nonsense we can close this issue.

**Comment by royvanv** [comment]
In my opinion it is clear enough.
