### ISSUE TITLE
Navbar component example: margin

### ISSUE THREAD

**Issue by asifm** [tailwindcss/docs#328]
In the [navigation component example page](https://tailwindcss.com/components/navigation/) [[source here](https://github.com/tailwindcss/docs/blob/master/source/components/navigation.blade.md)], I had to change `mr-` prefixes to `m-` for the `li` classes, in order for my navbars to look like what's shown on the page.

**Comment by adamwathan** [comment]
Must be some other mistake, this is the code copy and pasted right from the docs and looks exactly as expected:

https://tailwind.run/91Bq4e

You can even see if you inspect the component in the docs in devtools that it is using `mr-`.

Happy to take a look at your code if you want to share, nothing for us to correct here in the docs as far as I can tell though.

**Comment by asifm** [comment]
The "responsive header" example actually works fine (sorry for not having checked that one before creating the issue). The problem is in the other five examples, which use `ul`.

The first ("simple") example 
with `mr-`: https://tailwind.run/91Bq4e/1
with `m-`: https://tailwind.run/91Bq4e/2

(I'm having a lot of fun with tailwindcss. Amazing concept and superb implementation.)

**Comment by tlgreg** [comment]
The example in the docs is still right, the `ul` is just inside a container that has padding.

**Comment by asifm** [comment]
@tlgreg Is that mentioned somewhere and did I miss it?
