### ISSUE TITLE
UI display not okay after installing the tailwindcss offline documentation

### ISSUE THREAD

**Issue by jerexbambex** [tailwindcss/docs#363]
I install the tailwindcss documentation for offline access following the instruction, but after installation the look is not okay. It just like the css is not working.

**Comment by hacknug** [comment]
Are you opening the html files directly on your browser? You probably need to serve the site using somthing like [`http-server`](https://www.npmjs.com/package/http-server) or [Live Server](https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer).

**Comment by jerexbambex** [comment]
Yes I used jigsaw but it was not building so I had to copy the build folder into the bin directory. Now it works. Thanks
