### ISSUE TITLE
Search on tailwindcss website no longer works

### ISSUE THREAD

**Issue by mlieshout** [tailwindcss/docs#375]
Hi,

The searchfunction on the tailwindcss website doesn't work anymore. 
Safari console gives warnings about certificates:

<img width="1685" alt="Screenshot 2020-03-01 at 16 19 53" src="https://user-images.githubusercontent.com/994055/75628364-9d661d00-5bd8-11ea-9b22-be52ffda0121.png">

Firefox gives issues on loading alpine.js:

<img width="1032" alt="Screenshot 2020-03-01 at 16 22 56" src="https://user-images.githubusercontent.com/994055/75628415-051c6800-5bd9-11ea-8c98-3f5e197e2eb3.png">

**Comment by hacknug** [comment]
Just checked and it seems to work fine. Could this be cause by one of your extensions by any chance?

**Comment by mlieshout** [comment]
I don't think so. It suddenly works again. 

btw: https://tailwindui.com had the same issue.
