### ISSUE TITLE
A utility-first 

### ISSUE THREAD

**Issue by kaanguru** [tailwindcss/docs#390]
I think **A utility-first** should be replaced with **An utility-first**. I am not so confident in English language but it sounds strange to me.

![problem in text](https://user-images.githubusercontent.com/47606404/77318892-ea906700-6d1e-11ea-8308-434bd80b1c5d.png)

**Comment by adamwathan** [comment]
It's actually correct in this case although I can see how it's not intuitive for non-native English speakers!

This article looks like it explains it pretty well:

https://writingexplained.org/a-vs-an-difference

Thanks though!
