### ISSUE TITLE
fontFamily syntax in documentation is (maybe) incorrect

### ISSUE THREAD

**Issue by jamiesteven** [tailwindcss/docs#404]
https://github.com/tailwindcss/docs/source/docs/configuration.blade.md
https://github.com/tailwindcss/docs/source/docs/theme.blade.md

Both of these docs reference the following:

```
theme: {
  fontFamily: {
    display: ['Gilroy', 'sans-serif'],
    body: ['Graphik', 'sans-serif'],
  }
}
```

It appears this syntax doesn't work, or is out of date. I've found that this syntax does however work:

```
theme: {
  fontFamily: {
    sans: ['Roboto', 'sans-serif'],
    serif: ['Times New Roman', 'serif'],
    mono: ['Consolas', 'monospace']
  }
}
```

I'd be happy to make a pull-request to update those two docs with this change, if desired.

**Comment by adamwathan** [comment]
Hey! The docs are actually just trying to demonstrate how to _customize_ your configuration, so `display` and `body` are examples of changes you might make to the default config (if you wanted `font-display` and `font-body` classes for example).

You're right that if you wanted to customize the existing utilities you would use the names that match them 👍

**Comment by jamiesteven** [comment]
Thanks! Makes sense to me. My assumption was that display and body were somehow main classes that would effect all headline and body test classes.
