### ISSUE TITLE
Version number inconsistancy

### ISSUE THREAD

**Issue by jenstornell** [tailwindcss/docs#421]
## Home page - 1.4.0

![tailwindcss com_](https://user-images.githubusercontent.com/927011/81649293-5db97e00-9430-11ea-93f2-11ca7be7392c.png)

## Subpage 1.4.5

![tailwindcss com_docs_display_](https://user-images.githubusercontent.com/927011/81649291-5c885100-9430-11ea-89c6-bba9230cd2d8.png)

**Comment by adamwathan** [comment]
Needed to purge Cloudflare cache, thanks.
