### ISSUE TITLE
Drop down version problem

### ISSUE THREAD

**Issue by Nothing-Works** [tailwindcss/docs#477]
![screenshot-tailwindcss com-2020 07 22-11_27_48](https://user-images.githubusercontent.com/18606648/88117166-80c19480-cc0e-11ea-9bf3-787b81cc57c2.png)

As far as I can tell, it's still a version that was from 2 months ago.

I tried to test locally and it seemed fine.

Anyone can point me why this happening? is it because of caching? or something else thanks.

**Comment by royvanv** [comment]
The version number is manually updated.

@adamwathan: PR #472 has been merged, but the website hasn't been updated yet. Please update to 1.5.2 while you're at it.

**Comment by adamwathan** [comment]
It's Cloudflare caching, we cache all the HTML very aggressively for bandwidth reasons. Purging the cache now.
