### ISSUE TITLE
How to prevent permission denied error issue 

### ISSUE THREAD

**Issue by abrhambas01** [tailwindcss/docs#55]
I copied my offline docs from my windows 10 pc then I want to see it in my linux machine ? But I get this error : every time i do

```
$ npm run dev 

```
I get a 

>sh: /home/aebr/offline_docs/tailwindcss docs/docs/node_modules/.bin/cross-env: Permission denied error 

just like this 

![image](https://user-images.githubusercontent.com/12043306/48536598-07768800-e8ea-11e8-8d65-f4976a5e6589.png)

With regards to that, I made the basic fix, I found in the internet and remove the node_modules

```
rm -rf node_modules

rm package-lock.json yarn.lock

npm cache clear --force

npm install

```

but then now I get this : 

> /bin/sh: vendor/bin/jigsaw: Permission denied

**Comment by ruman63** [comment]
did you do `composer install` as sudo?

remove `vendor` and install as normal user,

```
sudo rm -rf vendor
composer install # without sudo
```
