### ISSUE TITLE
Documenatation

### ISSUE THREAD

**Issue by pjebs** [tailwindcss/docs#58]
I was wondering how I could get the template used for the documentation to use on my own stuff.
What it it's license too?

I'm mainly referring to the Look and Feel (ie. css etc) that Jigsaw uses.

**Comment by adamwathan** [comment]
Just transferred this from the main repo, but all the docs are here in this repo. Feel free to learn from it but please don't straight up steal the design.

**Comment by pjebs** [comment]
Isn't the design the same as Laravels?

**Comment by adamwathan** [comment]
Similar structure but the designs are completely different and were both designed separately from scratch by different people.

![image](https://user-images.githubusercontent.com/4323180/49051437-dcc3e380-f1b5-11e8-8fcb-3dcef6def8ea.png)

![image](https://user-images.githubusercontent.com/4323180/49051446-e3eaf180-f1b5-11e8-9d05-7485222b55f5.png)
