### ISSUE TITLE
What's the purpose of the 3rd value in rows passed to `_partials.class-table`?

### ISSUE THREAD

**Issue by benface** [tailwindcss/docs#62]
Here's an example:
```
@include('_partials.class-table', [
  'rows' => [
    [
      '.fill-current',
      'fill: currentColor;',
      'Set the fill color to the current text color.',
    ],
    [
      '.stroke-current',
      'stroke: currentColor;',
      'Set the stroke color to the current text color.',
    ],
  ]
])
```

The descriptive texts "Set the fill color to the current text color" and "Set the stroke color to the current text color" don't appear anywhere in the generated docs. Should they? All the rows in all the  `_partials.class-table` have a descriptive text like this.

**Comment by adamwathan** [comment]
They used to appear, I removed it to clean things up and make more room.

**Comment by benface** [comment]
Ah, ok. I don't think the docs really need these descriptions, I was mostly curious. Closing, thanks :)
