### ISSUE TITLE
Possible error in template provided for styles.css

### ISSUE THREAD

**Issue by vincent-octo** [tailwindcss/docs#72]
The [current documentation](https://tailwindcss.com/docs/installation#3-use-tailwind-in-your-css) provides a template for `styles.css` [0].
This template has `@tailwind components;` before `@tailwind utilities;`, which prevents the `center: true` from working (in my test and in tailwindcss/tailwindcss#446 ).

Should this template be changed so the order of `utilities` and `components` is switched?

[0]
```css
/**
 * This injects Tailwind's base styles, which is a combination of
 * Normalize.css and some additional base styles.
 *
 * You can see the styles here:
 * https://github.com/tailwindcss/tailwindcss/blob/master/css/preflight.css
 *
 * If using `postcss-import`, use this import instead:
 *
 * @import "tailwindcss/preflight";
 */
@tailwind preflight;

/**
 * This injects any component classes registered by plugins.
 *
 * If using `postcss-import`, use this import instead:
 *
 * @import "tailwindcss/components";
 */
@tailwind components;

/**
 * Here you would add any of your custom component classes; stuff that you'd
 * want loaded *before* the utilities so that the utilities could still
 * override them.
 *
 * Example:
 *
 * .btn { ... }
 * .form-input { ... }
 *
 * Or if using a preprocessor or `postcss-import`:
 *
 * @import "components/buttons";
 * @import "components/forms";
 */

/**
 * This injects all of Tailwind's utility classes, generated based on your
 * config file.
 *
 * If using `postcss-import`, use this import instead:
 *
 * @import "tailwindcss/utilities";
 */
@tailwind utilities;

/**
 * Here you would add any custom utilities you need that don't come out of the
 * box with Tailwind.
 *
 * Example :
 *
 * .bg-pattern-graph-paper { ... }
 * .skew-45 { ... }
 *
 * Or if using a preprocessor or `postcss-import`:
 *
 * @import "utilities/background-patterns";
 * @import "utilities/skew-transforms";
 */
```

**Comment by adamwathan** [comment]
Components should definitely come before utilities since utilities should be able to override component styles.

Can you link me to a GitHub repo that demonstrates `center: true` not working for the container? In the issue you linked it was because the person didn't have `@tailwind components` in their CSS at all, not because the order was different.

**Comment by vincent-octo** [comment]
Here is a test repo: https://github.com/vincent-octo/test_tailwind

**Comment by adamwathan** [comment]
How did you generate the `output.css` file? I don't see any package.json file listing your dependencies or build steps or anything.

My first guess is perhaps you forgot to pass the config file as an argument to the Tailwind CLI tool? This is the command you should be running:

`tailwind build styles.css -c tailwind.js -o output.css`

**Comment by vincent-octo** [comment]
Oh thanks!
I was indeed not passing the configuration file: `npx tailwind build styles.css > output.css`.
Somehow I thought it would use it by default.
