### ISSUE TITLE
Object Fit in documentation but not in CSS

### ISSUE THREAD

**Issue by TomS-** [tailwindcss/docs#77]
Simply, it doesn't apply any responsive styles, which also means it isn't activated at all. https://tailwindcss.com/docs/object-fit/

If this is intended it might be worth noting that this is disabled until at least on of the state modifications is applied.

**Comment by adamwathan** [comment]
Moved this to the docs repo as it's best solved by updating the docs page to make it clear it's not enabled by default. Will be a non-issue when 1.0 is open in a few weeks but if someone wanted to PR something to make it clear in the mean time I would be happy to merge it.
