### ISSUE TITLE
h2 overlapping interactive elements (Microsoft Edge)

### ISSUE THREAD

**Issue by ashgoldy** [tailwindcss/docs#79]
The h2 headings on the docs pages when using **Microsoft Edge** don't allow interaction with elements behind them.

Screenshot attached.

Works fine in Chrome/Firefox latest.

![tailwind-h2-overlap](https://user-images.githubusercontent.com/6873002/54029788-98c38000-41a1-11e9-84cd-282b1ff0e942.jpg)

**Comment by adamwathan** [comment]
This commit should fix!

https://github.com/tailwindcss/docs/commit/206cf36f5503e215ad76c088da31a713cbf8be21

Let me know if that solves it for you 👍

**Comment by ashgoldy** [comment]
Spot on!

Cheers 😃
