### ISSUE TITLE
[Feature Proposal] Output column on color table

### ISSUE THREAD

**Issue by fedeTibaldo** [tailwindcss/docs#9]
Yesterday, while I was browsing the docs, I found out that I'm not really good at deducing colors based on their hex notation. So, I thought that an ouput column would come in handy everytime you may want (or need) to use the default palette.
![immagine](https://user-images.githubusercontent.com/21128334/37388028-1c215138-275f-11e8-9a9c-46d8c4a3ae8b.png)
I guess that the same column could be implemented in the text-color table in a similar fashion.

I would be very fond of opening a pull request if you think it's useful!

**Comment by missmatsuko** [comment]
Can this be closed?

**Comment by hacknug** [comment]
I think so! //cc @adamwathan
